#!/usr/bin/env bash
# ops-render.sh — render project-layer agent files (.claude/agents/op-*.md) from
# templates + the tier config, so a PLAIN Agent dispatch can run on a non-Claude
# model (GLM via cc-proxy) without a workflow wrapping it.
#
# WHY (audit 2026-07-31 / spec 2026-07-28 §3.4): the workflow layer routes
# cross-provider via opts.model, but plain `Agent` dispatch reads the agent
# file's `model:` frontmatter at session start. The 5 shipped plugin-root
# agents carry a Claude tier alias (opus/sonnet/haiku) that check_agents
# REQUIRES. To bind a plain-dispatch seat to GLM, this writes a PROJECT-layer
# copy (.claude/agents/op-<seat>.md) that SHADOWS the plugin-root file by
# precedence, carrying the resolved model id. Plugin-root agents stay
# alias-only and validator-clean.
#
# PROBE-VERIFIED 2026-07-31: a plain Agent dispatch honors a non-Claude id in
# the file frontmatter (probe model: glm-5-turbo → replied glm-5-turbo).
#
# RESTART TO APPLY: agent files are read at session start, not reloaded
# mid-session (spec 2026-07-29:105). A render takes effect at the next session
# start; the command says so. M7: if CLAUDE_CODE_SUBAGENT_MODEL is set it
# overrides BOTH frontmatter and opts.model — detected and warned, not silently
# lost (spec 2026-07-29:71).
#
# FORMAT: the established tiers.env KEY=VAL convention (what ops-tiers.sh
# parses — pure shell/sed, parsed never sourced). One config file, two line
# kinds, both flat NAME=VALUE:
#   TIER:   JUDGMENT=claude-opus-5        (tier → model id)
#   SEAT:   op-mechanic=MECHANICAL        (seat → tier; 'op-' prefix optional)
# Layering matches ops-tiers.sh: baked → user → project. Seats merge by name.
#
# Guard chain inherits ops-tiers.sh's charset/routable (verified) + adds the
# writer half (spec §3.4 steps 4-8): seat-name guard, pre-validate, liveness
# probe, ownership-marked delete, two-pass atomic write. (The spec's
# last-known-good file was dropped in the F17 fix: it was written but never
# read — the RENDER_MARK ownership model subsumes it, revert = plugin-root.)
#
# Usage (from the project root):
#   ops-render.sh            render .claude/agents/op-*.md
#   ops-render.sh --show     print the resolved seat→model table
#   ops-render.sh --model <seat>   print ONE model id on stdout (scriptable)
#   ops-render.sh --revert   remove the project layer (fall back to plugin-root)
#   ops-render.sh --check    render to a temp dir + probe, write nothing
# Tier values (TRES_*) and provenance twins (TSRC_*) are set and read through
# `eval` (bash 3.2 on macOS has no associative arrays), so shellcheck cannot see
# either side of the use — same pattern, same directive, as ops-tiers.sh:27.
# shellcheck disable=SC2034,SC2154
set -eu

OPDIR=".operator"
OUTDIR=".claude/agents"
# Every rendered file carries this marker as its last line; render/revert
# delete ONLY marked files. The glob-delete version claimed the whole op-*
# namespace and destroyed a hand-authored .claude/agents/op-custom.md — and
# op-reviewer is a shipped agent but NOT a default seat, so customizing it via
# the documented shadowing mechanism created exactly the file render killed
# (audit F17). Unmarked files are never deleted; a name collision dies loudly.
RENDER_MARK='<!-- rendered-by: cc-operator ops-render — regenerated by render, removed by revert; do not hand-edit -->'
USER_FILE="${CC_OPERATOR_TIERS_USER:-$HOME/.claude/cc-operator/tiers.env}"
PROJ_FILE="${CC_OPERATOR_TIERS_PROJECT:-$OPDIR/tiers.env}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TPL_DIR="$SCRIPT_DIR/../agents/_templates"
AGENTS_DIR="$SCRIPT_DIR/../agents"   # plugin-root agents: the single-source seat bodies
PORT="${CC_PROXY_PORT:-4000}"

die() { echo "ops-render: $*" >&2; exit 2; }

# ── guards (mirror ops-tiers.sh check_routable + ledger check_bare_name)
# Well-formedness only, no id catalogue and no provider allowlist — see the
# resolver's copy for the full reasoning (0.8.3): the user picks the model,
# cc-proxy decides what it routes, operator decides neither.
check_routable() { # check_routable <label> <id>
  case "$2" in
    "") die "$1 is empty" ;;
    *[!A-Za-z0-9._:/@[\]-]*)
      die "$1='$2' contains characters outside [A-Za-z0-9._:/@[]-] (whitespace and quotes are never valid in a model id)" ;;
  esac
  return 0
}
check_seat_name() { # check_seat_name <name>
  # Allowlist, not blocklist: a seat name reaches a grep/awk pattern (seat_add),
  # an awk -v splice (render_to), and a filename (op-<seat>.md). The blocklist
  # version let regex metachars through — a seat 's.out' in tiers.env silently
  # DELETED the baked scout record via BRE '.' (audit F18). Anything outside
  # [A-Za-z0-9_-] is refused loudly; empty is refused too.
  case "$1" in
    "") die "seat name is empty" ;;
    *[!A-Za-z0-9_-]*) die "seat name '$1' contains characters outside [A-Za-z0-9_-]" ;;
  esac
}
is_tier_name() { case " $TIER_NAMES " in *" $1 "*) return 0 ;; *) return 1 ;; esac; }

TIER_NAMES="JUDGMENT IMPLEMENT MECHANICAL RECON"
# tier → model (resolved; defaults from ops-tiers.sh baked set)
TRES_JUDGMENT="claude-opus-5"; TRES_IMPLEMENT="claude-sonnet-5"
TRES_MECHANICAL="glm-5-turbo"; TRES_RECON="claude-haiku-4-5-20251001"
TSRC_JUDGMENT=default; TSRC_IMPLEMENT=default; TSRC_MECHANICAL=default; TSRC_RECON=default

# Default seat → tier (spec §3.3, plain-dispatch seats; review fan-out is the
# workflow's job, not here). Maps to the shipped aliases: opus→JUDGMENT,
# sonnet→IMPLEMENT, haiku→RECON.
# Stored as newline-separated "name|tier|src" records in SEATS.
SEATS=""

# seat_add <name> <tier> <src>: append (or override-by-name) a record. Builds
# the record list without a trailing-newline ambiguity: one record per line, no
# embedded blanks. The override filter compares the name FIELD literally (awk
# string equality) — never as a pattern: the grep -v version treated the seat
# name as a BRE, so 's.out' deleted 'scout' (audit F18). check_seat_name's
# allowlist is the first line of defense; this is the second.
seat_add() {
  local rest=""
  [ -n "$SEATS" ] && rest="$(printf '%s\n' "$SEATS" | awk -F'|' -v n="$1" '$1 != n')"
  if [ -z "$rest" ]; then SEATS="$1|$2|$3"; else SEATS="$rest"$'\n'"$1|$2|$3"; fi
}
# Default seat tiers MATCH the plugin-root aliases (opus→JUDGMENT,
# sonnet→IMPLEMENT, haiku→RECON or MECHANICAL — haiku is the only cheap alias,
# so both cheap tiers legitimately map to it). The first draft down-tiered
# author (JUDGMENT→IMPLEMENT) and mechanic (IMPLEMENT→MECHANICAL) against the
# spec §3.3 catalogue, the aliases, and this file's own comment — silently
# violating the charter's "judgment work never runs below judgment tier" on
# plain dispatch (audit F21). Cheapen deliberately via tiers.env, never by
# default. crawler/brainstorm are MECHANICAL by design: they are the cc-agents
# cheap-generation seats; their haiku alias is only the un-rendered fallback.
seat_add author JUDGMENT default
seat_add mechanic IMPLEMENT default
seat_add scout RECON default
seat_add verifier JUDGMENT default
seat_add crawler MECHANICAL default
seat_add brainstorm MECHANICAL default

# ── parse a tiers.env file (NAME=VALUE), parsed never sourced. Two line kinds:
#   NAME=<model-id>      → tier override  (if NAME is a known tier)
#   op-<seat>=<TIER>     → seat→tier       (the seat binding; 'op-' prefix optional)
# ops-tiers.sh already parses the tier kind the same way; this reuses that shape.
load_file() { # load_file <path> <source-label>
  [ -f "$1" ] || return 0
  # Mirrors ops-tiers.sh (F46): a NUL is checked BEFORE the loop, because bash
  # cannot hold one in a variable — no test on $line can see it, and the
  # plausible-looking `case "$line" in *$'\0'*)` is vacuously true ($'\0' is the
  # empty string, so the pattern is `**`) and rejects every valid config.
  # `read -d ''` returns 0 only if it truly reached a NUL. Needed because bash
  # 3.2's `read -n` stops AT a NUL, so a NUL-padded chunk passes the length
  # guard and its tail parses as a live seat binding.
  # The probe LOOPS over the file but is BOUNDED at 200 chunks (100KB) —
  # mirroring ops-tiers.sh. A single probe left NULs past byte 512 undetected
  # (Copilot 2026-08-03), so the loop must walk more than one chunk; but an
  # UNcapped loop walks a newline-less multi-MB tiers.env end-to-end and
  # stalls the renderer — measured 66-70s on 64MB vs 0.11s capped (bash
  # 3.2.57, 2026-08-04; the 4.0s from the F64 report is wrong by ~15x).
  # 200 chunks is the parse loop's own legal maximum (200 lines × 512
  # bytes); the first cap (40 chunks) rejected comment-heavy configs the parse
  # loop accepts (code-review of f4cae1a, 2026-08-04). Exceeding it is
  # malformed → fail closed. LC_ALL=C subshell so BOTH -n and ${#} count bytes —
  # a locale prefix on `read` alone leaves ${#} counting characters, and a
  # multibyte comment then false-positives as a NUL.
  if ! (LC_ALL=C _np=0
        while IFS= read -r -d '' -n 512 _nulprobe; do
          _np=$((_np + 1)); [ "$_np" -le 200 ] || exit 1
          [ "${#_nulprobe}" -eq 512 ] || exit 1
        done < "$1") 2>/dev/null; then
    die "$1: contains a NUL byte or exceeds 100KB — refusing (tiers.env is text, not a binary blob)"
  fi
  # LC_ALL=C so `read -n` (bytes on bash 3.2) and `${#line}` (chars in the
  # parent locale) agree on BYTES — a multibyte comment otherwise slips the
  # 512-cap guard and smuggles a seat binding (F42/F46 class; mirror of the
  # ops-tiers.sh fix, full-PR panel). Seat names and tiers are ASCII.
  local lc=0 name val LC_ALL=C
  while IFS= read -r -n 512 line || [ -n "$line" ]; do
    lc=$((lc + 1)); [ "$lc" -le 200 ] || die "$1: more than 200 lines — refusing"
    # Same guard as ops-tiers.sh: a chunk filling the 512 cap was truncated
    # mid-line, and its tail would be classified as a fresh line — turning the
    # comment check positional and letting a long comment smuggle a live
    # seat→tier binding past it (review panel, 2026-08-02).
    [ "${#line}" -lt 512 ] || die "$1: line $lc exceeds 512 chars — refusing (a tiers.env line is well under 80)"
    case "$line" in ''|'#'*) continue ;; esac
    [ "$line" != "${line%%=*}" ] || die "$1: malformed line (want NAME=VALUE): $line"
    name="${line%%=*}"; val="${line#*=}"
    name="${name#"${name%%[![:space:]]*}"}"; name="${name%"${name##*[![:space:]]}"}"
    val="${val#"${val%%[![:space:]]*}"}";  val="${val%"${val##*[![:space:]]}"}"
    case "$name" in
      *[[:space:]]*) die "$1: whitespace inside name '$name'" ;;
    esac
    # tier override?
    if is_tier_name "$name"; then
      check_routable "$name" "$val"
      eval "TRES_$name=\$val"; eval "TSRC_$name=\$2"
      continue
    fi
    # seat binding: strip an optional 'op-' prefix, must be a bare name, value a tier
    sname="${name#op-}"
    check_seat_name "$sname"
    is_tier_name "$val" || die "$1: seat '$sname' bound to unknown tier '$val' (known: $TIER_NAMES)"
    seat_add "$sname" "$val" "$2"
  done < "$1"
}
load_file "$USER_FILE" user
load_file "$PROJ_FILE" project

MODE=render
MODEL_SEAT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --show) MODE=show; shift ;; --revert) MODE=revert; shift ;;
    --check) MODE=check; shift ;;
    # --model <seat>: the resolver made SCRIPTABLE (#55). --show is a table for
    # a human — aligned columns, a header, a trailing note — and a caller that
    # wants one id has to parse it. This prints the id alone on stdout so a
    # dispatch site can substitute it directly.
    #
    # It resolves nothing new: the seat→tier map and check_routable already ran
    # at load time above, so this reads state the renderer itself uses. A second
    # resolver is what the coupling table exists to prevent.
    --model)
      MODE=model; shift
      [ $# -gt 0 ] || die "--model requires a seat name (see --show for the list)"
      MODEL_SEAT="$1"; shift ;;
    *) die "unknown argument '$1' (want --show|--model <seat>|--revert|--check)" ;; esac
done

# M7 guard: CLAUDE_CODE_SUBAGENT_MODEL overrides frontmatter AND opts.model. If
# it is set, every rendered binding silently loses to it — warn, do not fail
# (we cannot unset another process's env), but make the loss visible.
warn_subagent_env() {
  if [ -n "${CLAUDE_CODE_SUBAGENT_MODEL:-}" ]; then
    echo "ops-render: WARNING — \$CLAUDE_CODE_SUBAGENT_MODEL is set to '$CLAUDE_CODE_SUBAGENT_MODEL'; it OVERRIDES the rendered model: frontmatter at dispatch (spec M7). Unset it for the bindings below to take effect." >&2
  fi
}

# --model: exactly one id on stdout, nothing else. Every diagnostic goes to
# stderr so `M="$(ops-render.sh --model mechanic)"` is safe to substitute — a
# warning captured into the variable becomes a model id nobody configured.
[ "$MODE" = model ] && {
  # Same charset allowlist the renderer applies to a seat name from tiers.env:
  # this value reaches a grep pattern and an eval below, and a seat named `.*`
  # would match every record (F18, the reason check_seat_name is an allowlist).
  check_seat_name "$MODEL_SEAT"
  _mseat="${MODEL_SEAT#op-}"      # 'op-' prefix optional, as everywhere else
  _mtier=""
  # Field-exact match, never a pattern: the seat name is compared with string
  # equality inside the read loop for the same reason seat_add does it.
  while IFS='|' read -r -n 256 sn st ss; do
    [ -n "$sn" ] || continue
    [ "$sn" = "$_mseat" ] && { _mtier="$st"; break; }
  done <<EOF
$SEATS
EOF
  # An unknown seat is a REFUSAL, not an empty line: a caller substituting the
  # output would otherwise dispatch with an empty model and silently get the
  # harness default — the silent mis-route this whole guard family exists to
  # prevent. The known seats are named, because the likeliest cause is a typo.
  [ -n "$_mtier" ] || die "unknown seat '$MODEL_SEAT' (known: $(printf '%s\n' "$SEATS" | while IFS='|' read -r -n 256 sn _ _; do [ -n "$sn" ] && printf '%s ' "$sn"; done))"
  eval "_mid=\$TRES_$_mtier"
  # Defence in depth: check_routable already ran on every binding at load time,
  # so this cannot fire from tiers.env. It catches a DEFAULT that a future edit
  # breaks — the one path into TRES_* that never passes through the loader.
  check_routable "$_mseat" "$_mid"
  printf '%s\n' "$_mid"
  warn_subagent_env      # to stderr; the id on stdout stays clean
  exit 0
}

[ "$MODE" = show ] && {
  printf '%-12s %-12s %-32s %s\n' SEAT TIER MODEL SOURCE
  printf '%s\n' "$SEATS" | while IFS='|' read -r -n 256 sn st ss; do
    [ -n "$sn" ] || continue
    eval "mid=\$TRES_$st"
    printf '%-12s %-12s %-32s %s\n' "$sn" "$st" "$mid" "$ss"
  done
  echo; echo "render target: $OUTDIR/ (shadows plugin-root agents; restart to apply)"
  warn_subagent_env; exit 0
}

# remove_owned <dir>: delete only files stamped with RENDER_MARK. Prints the
# names it kept (unmarked op-*.md) so the operator sees what was preserved.
remove_owned() {
  local f kept=""
  for f in "$1"/op-*.md; do
    [ -f "$f" ] || continue
    if grep -qF "$RENDER_MARK" "$f" 2>/dev/null; then rm -f "$f"
    else kept="$kept ${f##*/}"; fi
  done
  [ -z "$kept" ] || echo "ops-render: kept (not renderer-owned):$kept"
}

[ "$MODE" = revert ] && {
  shopt -s nullglob
  remove_owned "$OUTDIR"
  shopt -u nullglob
  rmdir "$OUTDIR" 2>/dev/null || true
  rm -f "$OPDIR/.render-lastgood" 2>/dev/null || true   # drop the pre-F17 artifact if present
  echo "ops-render: reverted — removed rendered op-*.md; plugin-root (alias) agents now active (restart to apply)"
  exit 0
}

# ── render: two-pass atomic write (spec §3.4 steps 7-8) ─────────────────────
# render_to <dest>: emits op-<seat>.md with model: frontmatter set from the
# resolved tier id. Body source order:
#   1. agents/op-<seat>.md   (the plugin-root agent — SINGLE-SOURCE bodies:
#      the rendered copy keeps the seat's real contract, tools: line and
#      disallowedTools:. The template era rendered author/mechanic from
#      default.tmpl, which silently STRIPPED Write/Edit from both implementer
#      seats — audit F14.)
#   2. agents/_templates/<seat>.tmpl   (a custom seat with a shipped template)
#   3. agents/_templates/default.tmpl  (any other custom seat from tiers.env)
# Pure sed/awk frontmatter splice — no python.
render_to() { # render_to <dest>
  local dest="$1" sn st mid tpl
  mkdir -p "$dest"
  printf '%s\n' "$SEATS" | while IFS='|' read -r -n 256 sn st ss; do
    [ -n "$sn" ] || continue
    eval "mid=\$TRES_$st"
    tpl="$AGENTS_DIR/op-${sn}.md"
    [ -f "$tpl" ] || tpl="$TPL_DIR/${sn}.tmpl"
    [ -f "$tpl" ] || tpl="$TPL_DIR/default.tmpl"
    [ -f "$tpl" ] || die "no plugin-root agent or template for seat '$sn' and no $TPL_DIR/default.tmpl"
    # Splice model:/name: into frontmatter, replacing each line's VALUE. A
    # template carrying neither is rejected by the post-splice check below.
    #
    # `sub(/\r$/, "")` first: the delimiters anchor on /^---$/, which a CRLF
    # source never matches (`---\r` != `---`). Without the strip, infm never
    # sets, EVERY substitution branch is skipped, and the file copies through
    # verbatim carrying the template's stale model: value — a seat silently
    # bound to the wrong backend, exit 0. Normalizing also means the rendered
    # agent is LF regardless of how the source was saved.
    awk -v seat="op-$sn" -v model="$mid" '
      { sub(/\r$/, "") }
      BEGIN { infm=0; done_fm=0 }
      /^---$/ && !infm { infm=1; print; next }
      /^---$/ && infm && !done_fm { done_fm=1; print; next }
      infm && !done_fm {
        if ($0 ~ /^name:/) { sub(/:.*/, ": " seat, $0); print; next }
        if ($0 ~ /^model:/) { sub(/:.*/, ": " model, $0); print; next }
        print; next
      }
      { print }
    ' "$tpl" > "$dest/op-$sn.md"
    # Assert the splice LANDED — the resolved id is on the model: line — not
    # merely that a model: line exists. `grep -q '^model:'` cannot tell "spliced
    # correctly" from "never touched": it matches the template's own untouched
    # line just as happily. Exact-line compare in awk, so a model id containing
    # regex metacharacters needs no escaping.
    awk -v want="model: $mid" '$0 == want { found = 1 } END { exit !found }' \
      "$dest/op-$sn.md" ||
      die "$tpl: model: splice did not land (expected 'model: $mid') — a template with no model: frontmatter line renders an agent bound to the default backend"
    # Stamp ownership: render/revert delete only stamped files (F17).
    printf '\n%s\n' "$RENDER_MARK" >> "$dest/op-$sn.md"
  done
}

case "$MODE" in
  check)
    echo "ops-render: --check renders to a temp dir + probes; writes nothing."
    TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
    render_to "$TMP/agents"
    echo "--- distinct non-claude model ids ---"
    printf '%s\n' "$SEATS" | while IFS='|' read -r -n 256 sn st ss; do
      [ -n "$sn" ] || continue; eval "echo \$TRES_$st"; done \
      | sort -u | while IFS= read -r -n 256 id; do
        case "$id" in claude-*) echo "  $id: skipped (harness-served)"; continue ;; esac
        code="$(curl -sS -m 8 -o /dev/null -w '%{http_code}' -X POST \
          "http://127.0.0.1:${PORT}/v1/messages" -H 'content-type: application/json' \
          -d '{"model":"'"$id"'","max_tokens":1,"messages":[{"role":"user","content":"PONG"}]}' 2>/dev/null)" || code=000
        case "$code" in 2*) echo "  $id: probe OK ($code)" ;; *) echo "  $id: probe FAILED ($code)"; echo "FAIL" >&3 ;; esac
      done 3>&1 1>&2 | grep -q FAIL && die "a model id failed the liveness probe — refusing to render"
    echo "ops-render: --check passed."
    ;;
  render)
    [ -d "$TPL_DIR" ] || die "no templates dir at $TPL_DIR"
    warn_subagent_env
    TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
    render_to "$TMP/agents"
    mkdir -p "$OUTDIR"
    # A seat whose target name is taken by an UNMARKED file is a collision with
    # the user's own agent — refuse loudly rather than overwrite (F17). Checked
    # before any deletion so a failed render changes nothing.
    shopt -s nullglob
    for f in "$TMP/agents"/op-*.md; do
      t="$OUTDIR/${f##*/}"
      if [ -f "$t" ] && ! grep -qF "$RENDER_MARK" "$t" 2>/dev/null; then
        die "$t exists and is not renderer-owned (no render mark) — move or rename it, or pick a different seat name"
      fi
    done
    remove_owned "$OUTDIR"
    shopt -u nullglob
    mv "$TMP/agents"/op-*.md "$OUTDIR"/
    n="$(printf '%s\n' "$SEATS" | grep -c .)"
    echo "ops-render: rendered $n seat(s) to $OUTDIR/"
    echo "  RESTART THE SESSION for the new model bindings to take effect (agent files are read at session start)."
    ;;
esac
