#!/usr/bin/env bash
# ops-render.sh — render project-layer agent files (.claude/agents/op-*.md):
# plain Agent dispatch reads the agent file's model: frontmatter, so binding a
# seat to a cc-proxy model means writing a project-layer copy that SHADOWS the
# plugin-root file (which stays alias-only and validator-clean). Renders take
# effect at the NEXT session start; CLAUDE_CODE_SUBAGENT_MODEL overrides
# everything and is warned about (M7).
#
# tiers.env format (shared with ops-tiers.sh; parsed, never sourced):
#   TIER:   JUDGMENT=claude-opus-5        (tier → model id)
#   SEAT:   op-mechanic=MECHANICAL        (seat → tier; 'op-' prefix optional)
# Layering: baked → user → project. Seats merge by name.
#
# Usage (from the project root):
#   ops-render.sh            render .claude/agents/op-*.md
#   ops-render.sh --show     print the resolved seat→model table
#   ops-render.sh --model <seat>   print ONE model id on stdout (scriptable)
#   ops-render.sh --revert   remove the project layer (fall back to plugin-root)
#   ops-render.sh --check    render to a temp dir + probe, write nothing
# Tier values (TRES_*) and provenance twins (TSRC_*) are set and read through
# `eval` (bash 3.2 on macOS has no associative arrays), so shellcheck cannot see
# either side of the use — same pattern, same directive, as ops-tiers.sh:27.
# shellcheck disable=SC2034,SC2154
set -eu

OPDIR=".operator"
OUTDIR=".claude/agents"
# Every rendered file ends with this marker; render/revert delete ONLY marked
# files — a glob-delete once destroyed a hand-authored op-custom.md (F17).
# Unmarked files are never deleted; a name collision dies loudly.
RENDER_MARK='<!-- rendered-by: cc-operator ops-render — regenerated by render, removed by revert; do not hand-edit -->'
USER_FILE="${CC_OPERATOR_TIERS_USER:-$HOME/.claude/cc-operator/tiers.env}"
PROJ_FILE="${CC_OPERATOR_TIERS_PROJECT:-$OPDIR/tiers.env}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TPL_DIR="$SCRIPT_DIR/../agents/_templates"
AGENTS_DIR="$SCRIPT_DIR/../agents"   # plugin-root agents: the single-source seat bodies
PORT="${CC_PROXY_PORT:-4000}"

die() { echo "ops-render: $*" >&2; exit 2; }

# ── guards. check_routable: well-formedness only, no id catalogue — the user
# picks the model, cc-proxy routes it, operator decides neither (0.8.3).
check_routable() { # check_routable <label> <id>
  case "$2" in
    "") die "$1 is empty" ;;
    *[!A-Za-z0-9._:/@[\]-]*)
      die "$1='$2' contains characters outside [A-Za-z0-9._:/@[]-] (whitespace and quotes are never valid in a model id)" ;;
  esac
  return 0
}
check_seat_name() { # check_seat_name <name>
  # Allowlist: a seat name reaches awk/grep patterns and a filename — a
  # blocklist let 's.out' delete 'scout' via BRE '.' (F18).
  case "$1" in
    "") die "seat name is empty" ;;
    *[!A-Za-z0-9_-]*) die "seat name '$1' contains characters outside [A-Za-z0-9_-]" ;;
  esac
}
is_tier_name() { case " $TIER_NAMES " in *" $1 "*) return 0 ;; *) return 1 ;; esac; }

TIER_NAMES="JUDGMENT IMPLEMENT MECHANICAL RECON"
# tier → model (resolved; defaults from ops-tiers.sh baked set)
TRES_JUDGMENT="claude-opus-5"; TRES_IMPLEMENT="claude-sonnet-5"
TRES_MECHANICAL="glm-5-turbo"; TRES_RECON="claude-haiku-4-5-20251001"
TSRC_JUDGMENT=default; TSRC_IMPLEMENT=default; TSRC_MECHANICAL=default; TSRC_RECON=default

# Default seat → tier records, newline-separated "name|tier|src".
SEATS=""

# seat_add <name> <tier> <src>: append or override-by-name. The filter uses
# awk string equality, never a pattern (F18's second line of defense).
seat_add() {
  local rest=""
  [ -n "$SEATS" ] && rest="$(printf '%s\n' "$SEATS" | awk -F'|' -v n="$1" '$1 != n')"
  if [ -z "$rest" ]; then SEATS="$1|$2|$3"; else SEATS="$rest"$'\n'"$1|$2|$3"; fi
}
# Defaults MATCH the plugin-root aliases — a draft once down-tiered author and
# mechanic, silently violating "judgment work never runs below judgment tier"
# (F21). Cheapen deliberately via tiers.env, never by default.
seat_add author JUDGMENT default
seat_add mechanic IMPLEMENT default
seat_add scout RECON default
seat_add verifier JUDGMENT default
seat_add crawler MECHANICAL default
seat_add brainstorm MECHANICAL default

# ── parse a tiers.env file — bounded read, mirrors ops-tiers.sh exactly.
load_file() { # load_file <path> <source-label>
  [ -f "$1" ] || return 0
  # NUL probe BEFORE the loop (F46: bash drops NULs from variables; read -d ''
  # is the one builtin detector). Bounded at 200 chunks — unbounded stalls
  # ~66s on a newline-less 64MB file (F64). LC_ALL=C so -n and ${#} both
  # count BYTES; see ops-tiers.sh for the full history.
  if ! (LC_ALL=C _np=0
        while IFS= read -r -d '' -n 512 _nulprobe; do
          _np=$((_np + 1)); [ "$_np" -le 200 ] || exit 1
          [ "${#_nulprobe}" -eq 512 ] || exit 1
        done < "$1") 2>/dev/null; then
    die "$1: contains a NUL byte or exceeds 100KB — refusing (tiers.env is text, not a binary blob)"
  fi
  # LC_ALL=C on the loop too — bytes vs chars (F42/F46; mirror of ops-tiers).
  local lc=0 name val LC_ALL=C
  while IFS= read -r -n 512 line || [ -n "$line" ]; do
    lc=$((lc + 1)); [ "$lc" -le 200 ] || die "$1: more than 200 lines — refusing"
    # cap-filling chunk = truncated mid-line; die, don't parse the fragment
    [ "${#line}" -lt 512 ] || die "$1: line $lc exceeds 512 chars — refusing (a tiers.env line is well under 80)"
    case "$line" in ''|'#'*) continue ;; esac
    [ "$line" != "${line%%=*}" ] || die "$1: malformed line (want NAME=VALUE): $line"
    name="${line%%=*}"; val="${line#*=}"
    name="${name#"${name%%[![:space:]]*}"}"; name="${name%"${name##*[![:space:]]}"}"
    val="${val#"${val%%[![:space:]]*}"}";  val="${val%"${val##*[![:space:]]}"}"
    case "$name" in
      *[[:space:]]*) die "$1: whitespace inside name '$name'" ;;
    esac
    # tier override?
    if is_tier_name "$name"; then
      check_routable "$name" "$val"
      eval "TRES_$name=\$val"; eval "TSRC_$name=\$2"
      continue
    fi
    # seat binding: strip an optional 'op-' prefix, must be a bare name, value a tier
    sname="${name#op-}"
    check_seat_name "$sname"
    is_tier_name "$val" || die "$1: seat '$sname' bound to unknown tier '$val' (known: $TIER_NAMES)"
    seat_add "$sname" "$val" "$2"
  done < "$1"
}
load_file "$USER_FILE" user
load_file "$PROJ_FILE" project

MODE=render
MODEL_SEAT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --show) MODE=show; shift ;; --revert) MODE=revert; shift ;;
    --check) MODE=check; shift ;;
    # --model <seat> (#55): one id alone on stdout, directly substitutable.
    # Resolves nothing new — reads the state the renderer itself uses.
    --model)
      MODE=model; shift
      [ $# -gt 0 ] || die "--model requires a seat name (see --show for the list)"
      MODEL_SEAT="$1"; shift ;;
    *) die "unknown argument '$1' (want --show|--model <seat>|--revert|--check)" ;; esac
done

# M7: CLAUDE_CODE_SUBAGENT_MODEL overrides every rendered binding — warn,
# make the loss visible (we cannot unset another process's env).
warn_subagent_env() {
  if [ -n "${CLAUDE_CODE_SUBAGENT_MODEL:-}" ]; then
    echo "ops-render: WARNING — \$CLAUDE_CODE_SUBAGENT_MODEL is set to '$CLAUDE_CODE_SUBAGENT_MODEL'; it OVERRIDES the rendered model: frontmatter at dispatch (spec M7). Unset it for the bindings below to take effect." >&2
  fi
}

# --model: exactly one id on stdout; diagnostics to stderr so command
# substitution never captures a warning as a model id.
[ "$MODE" = model ] && {
  # the value reaches a pattern and an eval — same F18 allowlist as the loader
  check_seat_name "$MODEL_SEAT"
  _mseat="${MODEL_SEAT#op-}"      # 'op-' prefix optional, as everywhere else
  _mtier=""
  # field-exact string equality, never a pattern (F18)
  while IFS='|' read -r -n 256 sn st ss; do
    [ -n "$sn" ] || continue
    [ "$sn" = "$_mseat" ] && { _mtier="$st"; break; }
  done <<EOF
$SEATS
EOF
  # unknown seat = REFUSAL, not an empty line — an empty model silently
  # dispatches on the harness default
  [ -n "$_mtier" ] || die "unknown seat '$MODEL_SEAT' (known: $(printf '%s\n' "$SEATS" | while IFS='|' read -r -n 256 sn _ _; do [ -n "$sn" ] && printf '%s ' "$sn"; done))"
  eval "_mid=\$TRES_$_mtier"
  # catches a broken DEFAULT — the one path into TRES_* the loader never sees
  check_routable "$_mseat" "$_mid"
  printf '%s\n' "$_mid"
  warn_subagent_env      # to stderr; the id on stdout stays clean
  exit 0
}

[ "$MODE" = show ] && {
  printf '%-12s %-12s %-32s %s\n' SEAT TIER MODEL SOURCE
  printf '%s\n' "$SEATS" | while IFS='|' read -r -n 256 sn st ss; do
    [ -n "$sn" ] || continue
    eval "mid=\$TRES_$st"
    printf '%-12s %-12s %-32s %s\n' "$sn" "$st" "$mid" "$ss"
  done
  echo; echo "render target: $OUTDIR/ (shadows plugin-root agents; restart to apply)"
  warn_subagent_env; exit 0
}

# remove_owned <dir>: delete only files stamped with RENDER_MARK. Prints the
# names it kept (unmarked op-*.md) so the operator sees what was preserved.
remove_owned() {
  local f kept=""
  for f in "$1"/op-*.md; do
    [ -f "$f" ] || continue
    if grep -qF "$RENDER_MARK" "$f" 2>/dev/null; then rm -f "$f"
    else kept="$kept ${f##*/}"; fi
  done
  [ -z "$kept" ] || echo "ops-render: kept (not renderer-owned):$kept"
}

[ "$MODE" = revert ] && {
  shopt -s nullglob
  remove_owned "$OUTDIR"
  shopt -u nullglob
  rmdir "$OUTDIR" 2>/dev/null || true
  rm -f "$OPDIR/.render-lastgood" 2>/dev/null || true   # drop the pre-F17 artifact if present
  echo "ops-render: reverted — removed rendered op-*.md; plugin-root (alias) agents now active (restart to apply)"
  exit 0
}

# ── render: two-pass atomic write. Body source order: plugin-root
# agents/op-<seat>.md FIRST (single-source — the template era stripped
# Write/Edit from the implementer seats, F14), then <seat>.tmpl, then
# default.tmpl. Pure awk frontmatter splice.
render_to() { # render_to <dest>
  local dest="$1" sn st mid tpl
  mkdir -p "$dest"
  printf '%s\n' "$SEATS" | while IFS='|' read -r -n 256 sn st ss; do
    [ -n "$sn" ] || continue
    eval "mid=\$TRES_$st"
    tpl="$AGENTS_DIR/op-${sn}.md"
    [ -f "$tpl" ] || tpl="$TPL_DIR/${sn}.tmpl"
    [ -f "$tpl" ] || tpl="$TPL_DIR/default.tmpl"
    [ -f "$tpl" ] || die "no plugin-root agent or template for seat '$sn' and no $TPL_DIR/default.tmpl"
    # Splice model:/name: values into frontmatter. sub(/\r$/,"") first: the
    # /^---$/ anchors never match a CRLF source, which would copy the file
    # through verbatim with the template's stale model: value (F29).
    awk -v seat="op-$sn" -v model="$mid" '
      { sub(/\r$/, "") }
      BEGIN { infm=0; done_fm=0 }
      /^---$/ && !infm { infm=1; print; next }
      /^---$/ && infm && !done_fm { done_fm=1; print; next }
      infm && !done_fm {
        if ($0 ~ /^name:/) { sub(/:.*/, ": " seat, $0); print; next }
        if ($0 ~ /^model:/) { sub(/:.*/, ": " model, $0); print; next }
        print; next
      }
      { print }
    ' "$tpl" > "$dest/op-$sn.md"
    # Assert the splice LANDED (exact line, not "a model: line exists" —
    # grep -q matches the untouched template just as happily).
    awk -v want="model: $mid" '$0 == want { found = 1 } END { exit !found }' \
      "$dest/op-$sn.md" ||
      die "$tpl: model: splice did not land (expected 'model: $mid') — a template with no model: frontmatter line renders an agent bound to the default backend"
    # Stamp ownership: render/revert delete only stamped files (F17).
    printf '\n%s\n' "$RENDER_MARK" >> "$dest/op-$sn.md"
  done
}

case "$MODE" in
  check)
    echo "ops-render: --check renders to a temp dir + probes; writes nothing."
    TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
    render_to "$TMP/agents"
    echo "--- distinct non-claude model ids ---"
    printf '%s\n' "$SEATS" | while IFS='|' read -r -n 256 sn st ss; do
      [ -n "$sn" ] || continue; eval "echo \$TRES_$st"; done \
      | sort -u | while IFS= read -r -n 256 id; do
        case "$id" in claude-*) echo "  $id: skipped (harness-served)"; continue ;; esac
        code="$(curl -sS -m 8 -o /dev/null -w '%{http_code}' -X POST \
          "http://127.0.0.1:${PORT}/v1/messages" -H 'content-type: application/json' \
          -d '{"model":"'"$id"'","max_tokens":1,"messages":[{"role":"user","content":"PONG"}]}' 2>/dev/null)" || code=000
        case "$code" in 2*) echo "  $id: probe OK ($code)" ;; *) echo "  $id: probe FAILED ($code)"; echo "FAIL" >&3 ;; esac
      done 3>&1 1>&2 | grep -q FAIL && die "a model id failed the liveness probe — refusing to render"
    echo "ops-render: --check passed."
    ;;
  render)
    [ -d "$TPL_DIR" ] || die "no templates dir at $TPL_DIR"
    warn_subagent_env
    TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
    render_to "$TMP/agents"
    mkdir -p "$OUTDIR"
    # an UNMARKED file at the target is the user's own agent — refuse before
    # any deletion so a failed render changes nothing (F17)
    shopt -s nullglob
    for f in "$TMP/agents"/op-*.md; do
      t="$OUTDIR/${f##*/}"
      if [ -f "$t" ] && ! grep -qF "$RENDER_MARK" "$t" 2>/dev/null; then
        die "$t exists and is not renderer-owned (no render mark) — move or rename it, or pick a different seat name"
      fi
    done
    remove_owned "$OUTDIR"
    shopt -u nullglob
    mv "$TMP/agents"/op-*.md "$OUTDIR"/
    n="$(printf '%s\n' "$SEATS" | grep -c .)"
    echo "ops-render: rendered $n seat(s) to $OUTDIR/"
    echo "  RESTART THE SESSION for the new model bindings to take effect (agent files are read at session start)."
    ;;
esac
